name: Unity CI - Run Tests on Push

on:
    push:
        branches: [main, development]
    pull_request:
        branches: [main]
    workflow_dispatch:
        inputs:
            environment_name:
                description: dev or prod
                required: false

jobs:
    unity-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache Unity Library
              uses: actions/cache@v4
              with:
                  path: code/VR Art Gallery/Library
                  key: ${{ runner.os }}-unity-library-${{ hashFiles('code/VR Art Gallery/ProjectSettings/ProjectVersion.txt') }}

            - name: Check Unity secrets presence
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LISCENSE }}
                  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
              run: |
                  if [ -n "$UNITY_LICENSE" ]; then echo "UNITY_LICENSE: set"; else echo "UNITY_LICENSE: not set"; fi
                  if [ -n "$UNITY_SERIAL" ]; then echo "UNITY_SERIAL: set"; else echo "UNITY_SERIAL: not set"; fi
            - name: Run EditMode tests
              uses: game-ci/unity-test-runner@v4
              id: edit_tests
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LISCENCE }}
                  UNITY_EMAIL: ${{ secrets.U_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  unityVersion: auto
                  projectPath: "code/VR Art Gallery"
                  testMode: editmode

            - name: Upload EditMode test results
              uses: actions/upload-artifact@v4
              with:
                  name: editmode-test-results
                  path: code/VR Art Gallery/TestResults/EditModeResults.xml

            - name: Run PlayMode tests
              uses: game-ci/unity-test-runner@v2
              with:
                  unityVersion: auto
                  projectPath: "code/VR Art Gallery"
                  testMode: playmode
            - name: Upload PlayMode test results
              uses: actions/upload-artifact@v4
              with:
                  name: playmode-test-results
                  path: code/VR Art Gallery/TestResults/PlayModeResults.xml
